### ISSUE TITLE
Annotation `body.value` gets ignored

### ISSUE THREAD

**Issue by martimpassos** [stephenwf/iiif-builder#18]
I'm creating annotations with 
```
canvas.createAnnotationPage(annoPageId, (annoPage) => {
            const buildAnnotation = (canvasId, annoIndex, value) => {
              annoPage.createAnnotation({
                "id": `${canvasId}/annopage-2/anno-${annoIndex}`, 
                "type": "Annotation",
                "motivation": "commenting",
                "body": {
                  "type": "TextualBody",
                  "format": "text/html",
                  "value": value.note ? value.note : value,
                },
                "target": (value.x && value.y && value.width && value.height)
                  ? `${canvasId}#xywh=${value.x},${value.y},${value.width},${value.height}`
                  : canvasId
              })
            }
...
```

It works fine except that `value` (strings such as `"<p>Some annotation</p>"`) disappears in the output manifests. Am I doing something wrong or is some type check failing here?

**Comment by stephenwf** [comment]
@martimpassos I've opened #20 which is a breaking change (dependencies + types). However, it does fix this and a quite a few other bugs.

There is a sandbox here if you want to try it out.
https://codesandbox.io/p/sandbox/iiif-builder-w7pnxh?file=%2Fsrc%2Findex.js 

Also available as an NPM package:
```bash
# yarn 1
yarn add https://pkg.csb.dev/IIIF-Commons/iiif-builder/commit/d9a1e3fe/iiif-builder
# yarn 2, 3
yarn add iiif-builder@https://pkg.csb.dev/IIIF-Commons/iiif-builder/commit/d9a1e3fe/iiif-builder/_pkg.tgz
# npm
npm i https://pkg.csb.dev/IIIF-Commons/iiif-builder/commit/d9a1e3fe/iiif-builder
```

I'll keep the PR open, as I've not done too much testing with it yet, but your feedback would be appreciated!

**Comment by martimpassos** [comment]
Thanks, I installed it and can confirm it includes `body.value`s. I'll get back to you if I notice something else!

**Comment by stephenwf** [comment]
`v2.0.0` was published with this fix. A 2.0.0 of `iiif-builder` was published, but it will be the last tag. The package has also been renamed (to match other IIIF Commons repositories) to: `@iiif/builder`.
