### ISSUE TITLE
Support for creating collections within collections?

### ISSUE THREAD

**Issue by mathewjordan** [stephenwf/iiif-builder#2]
Hey @stephenwf. This is great stuff. I'm trying to use it to build collections on the fly and wondering if it can support building out collections with items of collections? Perhaps I'm just not making the correct call here.

When I attempt to call `collection.createCollection`, I'm getting the following:
Property 'createCollection' does not exist on type 'CollectionInstanceBuilder'.

`collection.createManifest` works like a charm. 👍 

For my full code:
```js
import { IIIFBuilder } from "iiif-builder";

const buildCollection = (data) => {
  const { id, label, summary, homepage, items } = data;

  const builder = new IIIFBuilder();

  return builder.createCollection(id, (collection) => {
    collection.addLabel(label, "none");
    collection.addSummary(summary, "none");
    collection.setHomepage({
      id: homepage,
    });
    items.forEach((item) => {
      collection.createCollection(item.id, (manifest) => {
        manifest.addLabel(item.label, "none");
        manifest.addSummary(item.summary, "none");
        manifest.setHomepage({
          id: homepage,
        });
        manifest.addThumbnail({
          id: "http://localhost:5001/...",
        });
      });
    });
  });
};

export { buildCollection };
```

**Comment by stephenwf** [comment]
Ah yes, looks like that was missing from the collection builder. Have added to #3.

**Comment by mathewjordan** [comment]
Thanks @stephenwf!
